#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    colorscheme = "one"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "nil"
    statusline_inactive_separator = "nil"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    relativenumber = false
    filetree_direction = 'left'
    lint_on_save = 0

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "git"

