#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &
#pgrep -x picom > /dev/null || picom -bc &

bspc monitor DP-0 -d 1 2 3 4 5
bspc monitor DP-2 -d 6 7 8 9 0

bspc config border_width         2
bspc config focused_border_color \#D19A66
bspc config normal_border_color \#505050
bspc config window_gap          20
bspc config top_padding		34
bspc config -m DP-2 top_padding	0
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false



# Run sxkhd
pgrep -x sxhkd > /dev/null || sxhkd &

# Run picom
pgrep -x picom > /dev/null || picom &
