
[colors.bright]
#black = "#6f7683"
black = "#6f7683"
blue = "#71bdf2"
cyan = "#65c1cd"
green = "#a7cb8b"
magenta = "#d190e3"
red = "#e78287"
white = "#fffefe"
yellow = "#daaa78"

[colors.cursor]
cursor = "#6f7683"
text = "#4a505d"

[colors.normal]
black = "#6f7683"
blue = "#71bdf2"
cyan = "#65c1cd"
green = "#a7cb8b"
magenta = "#d190e3"
red = "#e78287"
white = "#b9bfca"
yellow = "#daaa78"

[colors.primary]
background = "#242424"
#background = "#000000"
foreground = "#b9bfca"
